### ISSUE TITLE
What features should be supported?

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-contractrb#1]
- Token Feature
    - Issue/Transfer/Burn tokens
    - Support 3 token types(reissuable/non-reissuable/NFT)
- Timestamp Feature
    - Embed hash of data into OP_RETURN output

A sample ruby code using token feature is the following: 

```ruby
token = Token.new(params)

# issue token
token.issue!

# transfer
token.transfer!(to)

# burn
token.burn!

# other methods
token.issued? # confirmed?
token.burned?

```

A code of timestamp feature.

```ruby
timestamp = Timestamp.new(serializable_data, ...)
timestamp.save!

```

**Comment by azuchi** [comment]
In addition to above simple timestamp, I think there is a pattern of recording other facts (including single party and multi-marties) of who agreed to it.

**Comment by Yamaguchi** [comment]
I think scenario for simply transferring TPC is useful in some case.

```
transfer = Transfer.new(from_key, to_address, amount, other_parameter)
transfer.save!
```

**Comment by Yamaguchi** [comment]
I'll close this issue.

From now on, if each feature needs to be discussed, we will create an issue for it.
